image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pylint

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 yapp/*.py

pylint:
  stage: Static Analysis
  script:
    - pylint --ignore=wcsp.py --ignored-modules=scipy.special -E yapp/*.py
